apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-docs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-docs
  template:
    metadata:
      labels:
        app: plant-docs
    spec:
      containers:
      - name: plant-docs-api
        image: final-project:v1
        imagePullPolicy: Never 
        ports:
        - containerPort: 8000