apiVersion: v1
kind: Service
metadata:
  name: plant-docs-service
spec:
  type: NodePort
  selector:
    app: plant-docs
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007